version: "3.9"

services:
    db:
        container_name: db
        image: mysql:5.7
        env_file:
            - ./src/.dev.env
        build:
            context: ./db
        volumes:
            - data:/var/lib/mysql
        restart: on-failure
        networks:
            - network
    redis:
        container_name: redis
        image: redis:alpine
        volumes:
            - cache:/data
        restart: always
        networks:
            - network
        depends_on:
            - db
    server:
        container_name: server
        networks:
            - network
        env_file:
            - ./src/.dev.env
        build: ./src
        ports:
            - "3000:3000"
        depends_on:
            - db
            - redis
        restart: on-failure

networks:
    network:
        driver: bridge

volumes:
    data:
    cache:
