version: '3.9'

services:
    db:
        container_name: db
        image: mysql:5.7
        env_file:
            - .dev.env
        build:
            context: ./db
        volumes:
            - dev_data:/var/lib/mysql
        restart: on-failure
        ports:
            - 5679:3306
        networks:
            - network
    redis:
        container_name: redis
        image: redis:alpine
        volumes:
            - dev_cache:/data
        restart: always
        ports:
            - 6379:6379
        networks:
            - network
        depends_on:
            - db
networks:
    network:
        driver: bridge

volumes:
    dev_data:
    dev_cache:
