name: HelloWorld

on:
    pull_request:
        branches: [develop]
        types: [opened, synchronize, reopened]

jobs:
    say_hello:
        runs-on: windows-latest

        steps:
            - name: Say hello
              run: echo hello world
